---
- name: Deploy Node.js API
  hosts: api
  become: yes
  vars:
    app_dir: /opt/api
    git_repo: https://github.com/Kevinmrgt/DeploiementContinueEval.git
    git_branch: main
    node_version: 16.x
    local_api_dir: "/home/kevin/Documents/DEV/DeploiementTestIndividuel/api"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - git
          - curl
          - build-essential
        state: present

    - name: Add NodeSource repository
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }} | bash -
      args:
        creates: /etc/apt/sources.list.d/nodesource.list

    - name: Install Node.js and npm
      apt:
        name: nodejs
        state: present

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes
        state: present

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy package.json to VM
      copy:
        src: "{{ local_api_dir }}/package.json"
        dest: "{{ app_dir }}/package.json"
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Copy index.js to VM
      copy:
        src: "{{ local_api_dir }}/index.js"
        dest: "{{ app_dir }}/index.js" 
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Ensure routes directory exists
      file:
        path: "{{ app_dir }}/routes"
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy routes files
      copy:
        src: "{{ local_api_dir }}/routes/"
        dest: "{{ app_dir }}/routes/"
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Ensure utils directory exists
      file:
        path: "{{ app_dir }}/utils"
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy utils files
      copy:
        src: "{{ local_api_dir }}/utils/"
        dest: "{{ app_dir }}/utils/"
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Copy .env file to VM
      copy:
        src: "{{ local_api_dir }}/.env"
        dest: "{{ app_dir }}/.env"
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Set ownership of app directory
      file:
        path: "{{ app_dir }}"
        owner: vagrant
        group: vagrant
        recurse: yes

    - name: Install Node.js dependencies
      npm:
        path: "{{ app_dir }}"
        state: present
        production: yes
      become_user: vagrant

    - name: Check if PM2 is running the app
      shell: pm2 list | grep api-server
      register: pm2_status
      ignore_errors: yes
      become_user: vagrant

    - name: Start application with PM2
      shell: cd {{ app_dir }} && pm2 start index.js --name api-server
      become_user: vagrant
      when: pm2_status.rc != 0

    - name: Restart application with PM2 if already running
      shell: cd {{ app_dir }} && pm2 restart api-server
      become_user: vagrant
      when: pm2_status.rc == 0

    - name: Save PM2 process list
      shell: pm2 save
      become_user: vagrant

    - name: Set PM2 to start on boot
      shell: pm2 startup systemd -u vagrant --hp /home/vagrant
      when: pm2_status.changed
