name: Test et Package API

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: |
          cd api
          npm install
      
      - name: Run tests
        run: |
          cd api
          npm test
      
      - name: Create deployment package
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Création du package de déploiement pour la version $VERSION"
          mkdir -p deployment
          cp -r api deployment/
          cp -r ansible deployment/
          tar -czf api-deployment-$VERSION.tar.gz deployment
          echo "Package créé : api-deployment-$VERSION.tar.gz"
      
      - name: Print instructions
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "======================= INSTRUCTIONS DE DÉPLOIEMENT ======================="
          echo "✅ Tests réussis pour la version v$VERSION"
          echo "✅ Package de déploiement créé : api-deployment-$VERSION.tar.gz"
          echo ""
          echo "Pour déployer cette version :"
          echo "1. Téléchargez le package depuis l'onglet 'Actions' de GitHub"
          echo "2. Extrayez-le : tar -xzf api-deployment-$VERSION.tar.gz"
          echo "3. Déployez avec : cd deployment && ansible-playbook -i ansible/inventory.ini ansible/deploy.yml"
          echo "========================================================================"