name: Deploy API

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: |
          cd api
          npm install
      
      - name: Run tests
        run: |
          cd api
          npm test
      
      - name: Set up Ansible
        run: |
          pip install ansible
      
      - name: Check if SSH key is available
        id: check_ssh
        run: |
          if [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "ssh_available=true" >> $GITHUB_OUTPUT
          else
            echo "ssh_available=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Set up SSH key
        if: steps.check_ssh.outputs.ssh_available == 'true'
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy with Ansible
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
      
      - name: Check if Slack webhook is available
        id: check_slack
        run: |
          if [ -n "${{ secrets.SLACK_WEBHOOK }}" ]; then
            echo "slack_available=true" >> $GITHUB_OUTPUT
          else
            echo "slack_available=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Notify deployment status
        if: steps.check_slack.outputs.slack_available == 'true'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_TITLE: Deployment Status
          SLACK_MESSAGE: 'API deployment ${{ job.status }}'
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
